name: Release

on:
  push:
    branches:
      - master

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: tacoss/nodejs@v2
        with:
          args: make ci

      - run: |
          git config --local user.name "Release Bot"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: npm run release

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Publish
        run: make release && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
